name = "FDGrids"
uuid = "28eb41cd-435a-4ede-8bdb-f2685fc03e8c"
authors = ["Davide Lasagna <davide.lasagna@soton.ac.uk>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
