name = "FDGrids"
uuid = "28eb41cd-435a-4ede-8bdb-f2685fc03e8c"
authors = ["Davide Lasagna <davide.lasagna@soton.ac.uk>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
